"""Add avg_delay column

Revision ID: 726a6c99faa2
Revises: c97fd444c5c9
Create Date: 2025-12-08 13:36:43.045690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726a6c99faa2'
down_revision = 'c97fd444c5c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrape_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avg_delay', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrape_logs', schema=None) as batch_op:
        batch_op.drop_column('avg_delay')

    # ### end Alembic commands ###
